-- ###########################################
-- # Create Database
-- ###########################################

CREATE DATABASE ENTERPRISE_DB;


-- ###########################################
-- # Create
-- ###########################################

-- Create normal entities
    
CREATE TABLE MARKETINGAREA (
  ID BIGINT NOT NULL IDENTITY,
  STREAMID BIGINT NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  ISACTIVE BIT NOT NULL,
  CREATEDDATE DATETIME,
  CREATEDBY VARCHAR(50),
  LASTUPDATED DATETIME,
  LASTUPDATEDBY VARCHAR(50),
  VERSION BIGINT NOT NULL
);


CREATE TABLE CITY (
  ID BIGINT NOT NULL IDENTITY,
  NAME VARCHAR(100) NOT NULL,
  ZIPCODE VARCHAR(100) NOT NULL,
  ISACTIVE BIT NOT NULL,
  CREATEDDATE DATETIME,
  CREATEDBY VARCHAR(50),
  LASTUPDATED DATETIME,
  LASTUPDATEDBY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  MARKETINGAREA BIGINT NOT NULL
);


CREATE TABLE ENTSITEUSER (
  ID BIGINT NOT NULL IDENTITY,
  USERNAME VARCHAR(100) NOT NULL,
  FIRSTNAME VARCHAR(100) NOT NULL,
  LASTNAME VARCHAR(100) NOT NULL,
  EMAILADDRESS VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  ZIPCODE VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(100),
  ISACTIVE BIT NOT NULL,
  CREATEDDATE DATETIME,
  CREATEDBY VARCHAR(50),
  LASTUPDATED DATETIME,
  LASTUPDATEDBY VARCHAR(50),
  VERSION BIGINT NOT NULL
);


CREATE TABLE SITEBLOG (
  ID BIGINT NOT NULL IDENTITY,
  NAME VARCHAR(100) NOT NULL,
  ISACTIVE BIT NOT NULL,
  CREATEDDATE DATETIME,
  CREATEDBY VARCHAR(50),
  LASTUPDATED DATETIME,
  LASTUPDATEDBY VARCHAR(50),
  VERSION BIGINT NOT NULL
);


CREATE TABLE COMMENT (
  ID BIGINT NOT NULL IDENTITY,
  COMMENT VARCHAR(1000) NOT NULL,
  ISMODERATED BIT NOT NULL,
  CREATEDDATE DATETIME,
  CREATEDBY VARCHAR(50),
  LASTUPDATED DATETIME,
  LASTUPDATEDBY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  ENTSITEUSER BIGINT NOT NULL,
  SITEBLOG BIGINT NOT NULL
);



-- Create many to many relations
    

-- Primary keys
    
ALTER TABLE MARKETINGAREA ADD CONSTRAINT PK_MARKETINGAREA
	PRIMARY KEY (ID)
;

ALTER TABLE CITY ADD CONSTRAINT PK_CITY
	PRIMARY KEY (ID)
;

ALTER TABLE ENTSITEUSER ADD CONSTRAINT PK_ENTSITEUSER
	PRIMARY KEY (ID)
;

ALTER TABLE SITEBLOG ADD CONSTRAINT PK_SITEBLOG
	PRIMARY KEY (ID)
;

ALTER TABLE COMMENT ADD CONSTRAINT PK_COMMENT
	PRIMARY KEY (ID)
;

    

-- Unique constraints

ALTER TABLE MARKETINGAREA
	ADD CONSTRAINT UQ_MARKETINGAREA UNIQUE (ID)
;


ALTER TABLE CITY
	ADD CONSTRAINT UQ_CITY UNIQUE (ID)
;


ALTER TABLE ENTSITEUSER
	ADD CONSTRAINT UQ_ENTSITEUSER UNIQUE (ID)
;


ALTER TABLE SITEBLOG
	ADD CONSTRAINT UQ_SITEBLOG UNIQUE (ID)
;


ALTER TABLE COMMENT
	ADD CONSTRAINT UQ_COMMENT UNIQUE (ID)
;



-- Foreign key constraints
    

  
  
ALTER TABLE CITY ADD CONSTRAINT FK_CITY_MARKETINGAREA
	FOREIGN KEY (MARKETINGAREA) REFERENCES MARKETINGAREA (ID) ON DELETE CASCADE
;

  
  
  
  
  
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_ENTSITEUSER
	FOREIGN KEY (ENTSITEUSER) REFERENCES ENTSITEUSER (ID) ON DELETE CASCADE
;
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_SITEBLOG
	FOREIGN KEY (SITEBLOG) REFERENCES SITEBLOG (ID) ON DELETE CASCADE
;

  

    

-- Index


    